version: "3.8"

networks:
  kafka-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

services:
  kafka1:
    container_name: kafka1
    build: .
    ports:
      - "9094:9092"
      - "9192:9192"
    networks:
      kafka-net:
        ipv4_address: 172.20.0.11
    volumes:
      - ./config/kafka1/server.properties:/opt/kafka/config/server.properties
      - ./data/kafka1:/opt/kafka/data
    environment:
      KAFKA_HEAP_OPTS: "-Xmx1G -Xms1G"

  kafka2:
    container_name: kafka2
    build: .
    ports:
      - "9095:9092"
      - "9193:9192"
    networks:
      kafka-net:
        ipv4_address: 172.20.0.12
    volumes:
      - ./config/kafka2/server.properties:/opt/kafka/config/server.properties
      - ./data/kafka2:/opt/kafka/data
    environment:
      KAFKA_HEAP_OPTS: "-Xmx1G -Xms1G"

  kafka3:
    container_name: kafka3
    build: .
    ports:
      - "9096:9092"
      - "9194:9192"
    networks:
      kafka-net:
        ipv4_address: 172.20.0.13
    volumes:
      - ./config/kafka3/server.properties:/opt/kafka/config/server.properties
      - ./data/kafka3:/opt/kafka/data
    environment:
      KAFKA_HEAP_OPTS: "-Xmx1G -Xms1G"

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"
    networks:
      - kafka-net
    environment:
      KAFKA_CLUSTERS_0_NAME: local-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka1:9192,kafka2:9192,kafka3:9192
    depends_on:
      - kafka1
      - kafka2
      - kafka3
